#remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

theme: minima
author: radl_hirsch
description: Persönliche Tourensammlung

markdown: GFM

plugins:
  - jekyll-relative-links
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-admin
  - jekyll-seo-tag

relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - README.md
  - MTB.md
  - Wandern.md
  - Gravel.md
  
